version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: litebox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: litebox
      POSTGRES_PASSWORD: litebox
      POSTGRES_DB: litebox
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U litebox']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local




